version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/frontend"
    open-pull-requests-limit: 15
    schedule:
      interval: "daily"
    groups:
      frontend-deps:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/backend"
    open-pull-requests-limit: 15
    schedule:
      interval: "daily"
    groups:
      backend-deps:
        patterns:
          - "*"